### ISSUE TITLE
OncoKB Versions

### ISSUE THREAD

**Issue by jalavery** [karissawhiting/oncokbR#10] opened 2023-02-10 20:10 UTC
It looks like oncoKB has releases fairly frequently: https://www.oncokb.org/news
Could be good to think about incorporating a parameter to access specific versions to improve reproducibility.

In Dec, I had run oncoKB twice in a few days and discovered that the discrepancy across the runs was due to a different data version returned by the API call.

**Comment by karissawhiting** [comment] 2023-10-03 19:20
That's a great point. That's happened to me as well. I'm actually not sure how the API itself handles the different data versions. I'm guessing it remains the same but pulls from different versions of the database itself. I wonder if you can direct it to pull from older versions? I will have to look into it or maybe @inodb knows something about this?

**Comment by inodb** [comment] 2023-10-03 19:24
Passing the ball onto @zhx828 who is the lead developer of OncoKB

**Comment by zhx828** [comment] 2023-10-03 19:57
> Passing the ball onto @zhx828 who is the lead developer of OncoKB

Thanks @inodb . @karissawhiting @jalavery Hey there! We've got plans to provide access to previous versions of OncoKB, but right now, we're a bit short-handed to make it happen immediately. We've got some ideas on how to go about it though.

In an ideal world, you'd be able to specify the data version you want to annotate using a parameter. But the earliest I can see us getting to work on this is early next year.

In the meantime, if you've got a specific data version in mind that you'd like to use, I can set it up for you. You'd just need to change the OncoKB URL to point to that version. We don't advertise this much because those older versions are running on limited resources, so they might not be as stable or fast as the [www.oncokb.org](http://www.oncokb.org/) site.

For instance, we support the following versions
- data-4-5.oncokb.org
- data-4-0.oncokb.org
- data-3-11.oncokb.org

**Comment by karissawhiting** [comment] 2023-10-03 20:02
Thanks @zhx828, that info is super helpful! I don't have a specific need at the moment, just thinking about reproducibility of research pipelines in general. Good to know that exists as an option!

For now I'm going to close this and keep an eye out for the added versioning parameter you describe in the future. Thanks!

**Closed by karissawhiting** 2023-10-03 20:02 UTC
Labels: hackathon
